# Generated by Django 6.0.2 on 2026-02-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
