# Generated by Django 6.0.2 on 2026-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrolled',
            field=models.CharField(choices=[('ED', 'Edinburg'), ('BR', 'Brownsville'), ('BO', 'Both')], default='ED', max_length=20),
        ),
    ]
