# Generated by Django 6.0.2 on 2026-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_remove_profile_student_id_alter_profile_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrolled',
            field=models.CharField(choices=[('ED', 'Edinburg'), ('BR', 'Brownsville')], default='ED', max_length=20),
        ),
    ]
