# Generated by Django 6.0.2 on 2026-04-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
