# Generated by Django 6.0.4 on 2026-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='defaultpfp.png', upload_to='profile_pics/'),
        ),
    ]
